---
title: "H3K27ac_CorrelationHeatMap"
output: html_document
date: "2026-01-30"
---

```{r setup, include=FALSE, warning = FALSE, message=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png","pdf")
)
```

```{r Setting_Up_Enviroment, results="hide"}

####Library Loading####
library("edgeR")
library("ggplot2")
library("tibble")
library("dplyr")
library("ggrepel")
library("readr")
library("org.Hs.eg.db")
library("AnnotationDbi")
library("pheatmap")
library("Cormotif")
library("tidyverse")
library("workflowr")
library("RUVSeq")
library("SummarizedExperiment")
library("readxl")
library("ggfortify")
library("ComplexHeatmap")

H3K27ac_Metadata <- readRDS("data/Raw_Data/H3K27ac_MetaData.RDS")
H3K27ac_fc_df <- readRDS("data/Raw_Data/H3K27ac_fc_df.RDS")
H3K27ac_joined_fc <- readRDS("data/Raw_Data/H3K27ac_joined_fc.RDS")
Filt_2M_H3K27ac_log2cpm <- readRDS("data/QC/Filt_2M_H3K27ac_log2cpm.RDS")
Filt_2M_RMG0_H3K27ac_fc <- readRDS("data/QC/Filt_2M_RMG0_H3K27ac_fc.RDS")
Filt_2M_RMG0_H3K27ac_log2cpm <- readRDS("data/QC/Filt_2M_RMG0_H3K27ac_log2cpm.RDS")
```


```{r Setting_Up_Data, results="hide"}

H3K27ac_Metadata <- read_excel("~/diff_timeline_tes/H3K27ac/H3K27ac_Metadata.xlsx")
saveRDS(H3K27ac_Metadata,"data/Raw_Data/H3K27ac_MetaData.RDS")

h_samples_counts <- read.delim("~/ASHG_Data/FeatureCounts/ASHG_h_samples_counts_2pSTP_noD4.txt", comment.char="#")
c_samples_counts <- read.delim("~/ASHG_Data/FeatureCounts/ASHG_c_samples_counts_2pSTP_noD4.txt", comment.char="#")
H3K27ac_joined_fc <- left_join(h_samples_counts,c_samples_counts,by="Geneid")
# saveRDS(H3K27ac_joined_fc,"data/Raw_Data/H3K27ac_joined_fc.RDS")

#To keep only OrthoGenes and sample columns
H3K27ac_fc <- H3K27ac_joined_fc[ , !(names(H3K27ac_joined_fc) %in% c("gene","Chr.x","Start.x","End.x","Strand.x","Length.x","Geneid.x","Chr.y","Start.y","End.y","Strand.y","Length.y","Geneid.y"))]
# 89 columns; 7 x 6 = 42 Human Exp, 7 x 6 = 42 Chimp Exp, 4 Human Replicate
dim(H3K27ac_joined_fc)
H3K27ac_fc <- H3K27ac_fc %>% 
  column_to_rownames("Geneid")

#Rename column Names to More Useful Info
col_names <- H3K27ac_Metadata$SampleName

colnames(H3K27ac_fc) <- col_names
dim(H3K27ac_fc)

sum(duplicated(rownames(H3K27ac_fc)))

H3K27ac_fc_df <- as.data.frame(H3K27ac_fc)

# saveRDS(H3K27ac_fc_df,"data/Raw_Data/H3K27ac_fc_df.RDS")

```


```{r H3K27acSeq_FeatureCounts_Box_Unfiltered}
#####Unfiltered####
H3K27ac_fc <-H3K27ac_fc %>%
  as_tibble(.name_repair = "unique")

H3K27ac_fc <- H3K27ac_fc_df %>%
  dplyr::select(-ends_with("_IgG"))%>%
  dplyr::select(-c("C40210_Day15","C3649_Day4","C3647_Day30","H24280_Day2"))

H3K27ac_Metadata <- H3K27ac_Metadata %>%
  dplyr::filter(!grepl("_IgG$", SampleName))

H3K27ac_Metadata <- H3K27ac_Metadata %>% 
  dplyr::filter(!grepl("C40210_Day15",SampleName)) %>% 
  dplyr::filter(!grepl("C3649_Day4",SampleName)) %>% 
  dplyr::filter(!grepl("C3647_Day30",SampleName)) %>% 
  dplyr::filter(!grepl("H24280_Day2",SampleName))


# saveRDS(H3K27ac_Metadata,"data/QC/H3K27ac_Metadata.RDS")

Filt_2M_H3K27ac_log2cpm <- cpm(H3K27ac_fc,log=TRUE)
print(hist(Filt_2M_H3K27ac_log2cpm,  main = "Histogram of all counts (>2M reads)",
     xlab =expression("Log"[2]*" counts-per-million"), col =4 ))

boxplot(Filt_2M_H3K27ac_log2cpm, main = "Boxplots of log cpm per sample
          (>2M Reads)", xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.3)        # shrink label size
# saveRDS(Filt_2M_H3K27ac_log2cpm,"data/QC/Filt_2M_H3K27ac_log2cpm.RDS")
```



```{r H3K27acSeq_FeatureCounts_RMG0}

#####RowMu>0####
row_means <- rowMeans(Filt_2M_H3K27ac_log2cpm)
Filt_2M_RMG0_H3K27ac_fc <- H3K27ac_fc[row_means >0,]
# saveRDS(Filt_2M_RMG0_H3K27ac_fc,"data/QC/Filt_2M_RMG0_H3K27ac_fc.RDS")

Filt_2M_RMG0_H3K27ac_log2cpm <- cpm(Filt_2M_RMG0_H3K27ac_fc,log=TRUE)
dim(H3K27ac_fc)
dim(Filt_2M_RMG0_H3K27ac_log2cpm)

# saveRDS(Filt_2M_RMG0_H3K27ac_log2cpm,"data/QC/Filt_2M_RMG0_H3K27ac_log2cpm.RDS")

hist(Filt_2M_RMG0_H3K27ac_log2cpm, main = "Histogram of filtered counts using rowMeans > 0 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

#####RowMu>1####
row_means <- rowMeans(Filt_2M_H3K27ac_log2cpm)
Filt_2M_RMG1_H3K27ac_fc <- H3K27ac_fc[row_means >1,]
# saveRDS(Filt_2M_RMG1_H3K27ac_fc,"data/QC/Filt_2M_RMG1_H3K27ac_fc.RDS")

Filt_2M_RMG1_H3K27ac_log2cpm <- cpm(Filt_2M_RMG1_H3K27ac_fc,log=TRUE)
dim(H3K27ac_fc)
dim(Filt_2M_RMG1_H3K27ac_log2cpm)

# saveRDS(Filt_2M_RMG1_H3K27ac_log2cpm,"data/QC/Filt_2M_RMG1_H3K27ac_log2cpm.RDS")

hist(Filt_2M_RMG1_H3K27ac_log2cpm, main = "Histogram of filtered counts using rowMeans > 1 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )

#####RowMu>2####
row_means <- rowMeans(Filt_2M_H3K27ac_log2cpm)
Filt_2M_RMG2_H3K27ac_fc <- H3K27ac_fc[row_means >2,]
# saveRDS(Filt_2M_RMG2_H3K27ac_fc,"data/QC/Filt_2M_RMG2_H3K27ac_fc.RDS")

Filt_2M_RMG2_H3K27ac_log2cpm <- cpm(Filt_2M_RMG2_H3K27ac_fc,log=TRUE)
dim(H3K27ac_fc)
dim(Filt_2M_RMG2_H3K27ac_log2cpm)

# saveRDS(Filt_2M_RMG2_H3K27ac_log2cpm,"data/QC/Filt_2M_RMG2_H3K27ac_log2cpm.RDS")

hist(Filt_2M_RMG2_H3K27ac_log2cpm, main = "Histogram of filtered counts using rowMeans > 2 method",
     xlab =expression("Log"[2]*" counts-per-million"), col =5 )



```

```{r H3K27acSeq_FeatureCounts_Box_RMG0}
boxplot(Filt_2M_RMG0_H3K27ac_log2cpm, main = "Boxplots of log cpm per sample (RowMeans>0)",xaxt = "n", xlab= "")
axis(1,
     at = 1:length(col_names),  # positions (one per sample)
     labels = col_names,        # your labels vector
     las = 2,               # rotate text vertically (like srt=90)
     cex.axis = 0.3)        # shrink label size

```

```{r H3K27acSeq_FeatureCounts_Cor_RMG0}
######Cor_HeatMap####
Cor_Filt_2M_RMG0_H3K27ac_log2cpm <- cor(Filt_2M_RMG0_H3K27ac_log2cpm, method = "spearman")
individual <- H3K27ac_Metadata$Individual
species <- H3K27ac_Metadata$Species
timepoint <- H3K27ac_Metadata$Timepoint
timepoint <- factor(timepoint,levels = c("Day0","Day2","Day4","Day5","Day15","Day30"))
Cor_metadata <- data.frame(
  sample_cor = colnames(Filt_2M_RMG0_H3K27ac_log2cpm),
  species_cor = species,
  timepoint_cor = timepoint,
  individual_cor = individual
)


ann_colors <- list(
  timepoint_cor = c(
    "Day0" = "#883268",   # Purple
    "Day2" = "#3E7274",  # blue
    "Day4" = "#5AAA464D",  # light green
    "Day5" = "#94C47D",  # Green
    "Day15" = "#C03830",  # red
    "Day30" = "#830C05"  # dark red
  ),
  species_cor = c(
    "H" = "#171717",  # black
    "C" = "#17171717"   # light grey
  ),
  individual_cor = c(
    H1 = "#091638", #Blue-Green Darkest
    H2 = "#11185B",
    H3 = "#0F2C71",
    H4 = "#0D568F",
    H4R = "#0D568F",
    H5 = "#1D8296",
    H6 = "#46A389",
    H7 = "#9DD484", #Blue-Green Lightest
    C1 = "#340702", #Brown-Orange darkest
    C2 = "#5D0B02",
    C3 = "#951302",
    C4 = "#D32804",
    C5 = "#F74019",
    C6 = "#FA7A38",
    C7 = "#FCC598"
    
  )
)
rownames(Cor_metadata) <- Cor_metadata$sample_cor

# saveRDS(Cor_Filt_RMG0_H3K27ac_log2cpm, "data/QC/Cor_Filt_RMG0_H3K27ac_log2cpm.RDS")
# saveRDS(Cor_metadata, "data/QC/Cor_H3K27ac_metadata.RDS")
# saveRDS(ann_colors,"data/QC/ann_colors.RDS")

```

```{r H3K27acSeq_FeatureCounts_HeatMap_RMG0,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_2M_RMG0_H3K27ac_log2cpm,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation \n(Spearman-log2CPM-RowMeans>0)")
)
```

```{r H3K27acSeq_FeatureCounts_RMG0_No4}

####Subset####
H3K27ac_Metadata_No4 <- H3K27ac_Metadata %>% 
 filter(Timepoint != "Day4")

H3K27ac_fc_NoD4 <- H3K27ac_fc %>% 
  dplyr::select(-ends_with("_Day4"))

H3K27ac_log2cpm_NoD4 <- cpm(H3K27ac_fc_NoD4,log=TRUE)
dim(H3K27ac_log2cpm_NoD4)
dim(H3K27ac_fc)
row_means_NoD4 <- rowMeans(H3K27ac_log2cpm_NoD4)
Filt_RMG0_H3K27ac_fc_NoD4 <- H3K27ac_fc_NoD4[row_means_NoD4 >0,]
dim(Filt_RMG0_H3K27ac_fc_NoD4)
Filt_RMG0_H3K27ac_log2cpm_NoD4 <- cpm(Filt_RMG0_H3K27ac_fc_NoD4,log=TRUE)

saveRDS(H3K27ac_Metadata_No4,"data/QC/H3K27ac_Metatdata_No4.RDS")
saveRDS(Filt_RMG0_H3K27ac_fc_NoD4,"data/QC/Filt_RMG0_H3K27ac_fc_NoD4.RDS")
saveRDS(Filt_RMG0_H3K27ac_log2cpm_NoD4, "data/QC/Filt_RMG0_H3K27ac_log2cpm_NoD4.RDS")

```

```{r rH3K27acSeq_FeatureCounts_Cor_RMG0_No4}
######Cor_HeatMap####
Cor_Filt_RMG0_H3K27ac_log2cpm_NoD4 <- cor(Filt_RMG0_H3K27ac_log2cpm_NoD4, method = "spearman")

Cor_metadata_No4 <- Cor_metadata %>% 
  dplyr::filter(timepoint_cor !="Day4")

ann_colors_No4 <- ann_colors
ann_colors_No4$timepoint_cor <- ann_colors$timepoint_cor[
  names(ann_colors$timepoint_cor) != "Day4"
]

# saveRDS(Cor_metadata_No4, "data/QC/Cor_metadata_No4.RDS")
# saveRDS(Cor_Filt_RMG0_H3K27ac_log2cpm_NoD4, "data/QC/Cor_Filt_RMG0_H3K27ac_log2cpm_NoD4.RDS")
# saveRDS(ann_colors_No4,"data/QC/ann_colors_no4.RDS")
```


```{r rH3K27acSeq_FeatureCounts_HeatMap_RMG0_No4,fig.height=10,fig.width=10}
print(
  pheatmap(Cor_Filt_RMG0_H3K27ac_log2cpm_NoD4,
         fontsize_row = 5,
         fontsize_col = 5,
         annotation_col = Cor_metadata_No4[, c("species_cor", "timepoint_cor","individual_cor")],
         annotation_colors = ann_colors_No4,
         clustering_distance_rows = "correlation",
         clustering_distance_cols = "correlation",
         main = "Sample-Sample Correlation (Spearman) \n (log2CPM-RowMeans>0-NoDay4)")
)
```



```{r H3K27acSeq_FeatureCounts_RMG0_No4_RUV}
filt_gene_list <- rownames(Filt_RMG0_H3K27ac_log2cpm_NoD4)
#14838
length(filt_gene_list)


# # in order to make this match with annot later down the line, change the col names for counts_raw_matrix to match final_sample_names in annot
# 
# # i'll also want to make sure I keep the replicate for this set
# 
# Ind_RUV <- c(rep("H1",5),
#              rep("H2",5),
#              rep("H3",5),
#              rep("H4",5),
#              rep("H5",5),
#              rep("H6",5),
#              rep("H7",5),
#              rep("H4R",4),
#              rep("C1",5),
#              rep("C2",5),
#              rep("C3",5),
#              rep("C4",5),
#              rep("C5",5),
#              rep("C6",5),
#              rep("C7",5)
#              )
# H3K27ac_Metadata_No4$Ind_RUV <- Ind_RUV
# H3K27ac_Metadata_No4_RUV <- H3K27ac_Metadata_No4 %>%
#    mutate(
#     Ind_RUV = factor(Ind_RUV,
#                         levels = c("H1","H2","H3","H4","H5","H6","H7","H4R","C1","C2","C3","C4","C5","C6","C7"),ordered=TRUE),
#     Timepoint = factor(Timepoint,
#                        levels = c("Day0","Day2","Day5","Day15","Day30"),ordered=TRUE),
#     Species = factor(Species,
#                      levels = c("H","C"),ordered=TRUE),
#     Condition = factor(
#       Condition,
#       levels = expand.grid(
#         Ind_RUV = levels(Ind_RUV),
#         Timepoint = levels(Timepoint),
#         Species = levels(Species)
#       ) %>%
#         transmute(Condition=paste(Species,Timepoint,Ind_RUV,sep="_")) %>%
#         pull(Condition),
#       ordered=TRUE
#     )
#   )
# 
# # saveRDS(H3K27ac_Metadata_No4_RUV,"data/QC/H3K27ac_MetaData_NoD4_RUV.RDS")
# H3K27ac_Metadata_No4_RUV <- readRDS("data/QC/H3K27ac_MetaData_NoD4_RUV.RDS")
# 
# H3K27ac_fc_NoD4_RUV <- H3K27ac_fc_NoD4
# colnames(H3K27ac_fc_NoD4_RUV) <- H3K27ac_Metadata_No4_RUV$Condition
# 
# RUV_filt_counts <- H3K27ac_fc_NoD4_RUV %>% 
#   as.data.frame() %>% 
#   dplyr::filter(., row.names(.)%in% filt_gene_list)
# # saveRDS(RUV_filt_counts, "data/DGE/RUV_filt_counts.RDS")
# dim(RUV_filt_counts)
# 
# #add in the annotation files
# ind_num <- H3K27ac_Metadata_No4_RUV$Ind_RUV
# type(ind_num)
# length(ind_num)
# 
# annot <- as.data.frame(H3K27ac_Metadata_No4_RUV)
# type(annot)
# is.data.frame(annot)
# #same as Metadata
# 
# 
# #  counts need to be integer values and in a numeric matrix
# # note: the log transformation needs to be accounted for in the isLog argument in RUVs function.
# counts <- as.matrix(RUV_filt_counts)
#   
# # saveRDS(counts, "data/QC/filt_counts_matrix.RDS")
# 
# # Create a DataFrame for the phenoData
# phenoData <- DataFrame(annot)
# 
# set <- SummarizedExperiment(assays = counts, metadata = phenoData)
# 
# scIdx <- RUVSeq::makeGroups(phenoData$Cond)
# 
# # # Generate a background matrix
# # # The column "Cond" holds the comparisons that you actually want to make. DOX_24, DMSO_24,5FU_24, DOX_3,etc.
# # Day0 <- c(16,36)
# # Day2 <- c(17,37)
# # Day5 <- c(18,38)
# # Day30 <- c(20,39)
# # scIdx <- rbind(Day0,Day2,Day5,Day30)
# # rownames(scIdx) <- c("[1,]","[2,]","[3,]","[4,]")
# # colnames(scIdx) <- c("[,1]","[,2]")
# ```
# 
# 
# 
# ```{r}
# #now I've made all of the data I need for this - they are located in each section for k values
# 
# #DO NOT USE THESE COUNTS FOR LINEAR MODELING
# 
# #colors for all of the plots
# # txtime_col
# # ind_col
# # time_col
# # tx_col
# log2cpm <- cpm(counts,log=TRUE)
# # before ruv (counts PCA)
# prcomp_res_log2 <- prcomp(t(Filt_RMG0_H3K27ac_log2cpm_NoD4), scale=FALSE, center = TRUE)
# annot_prcomp_res <- prcomp_res_log2$x %>% cbind(., annot)
# # 
# # group_2 <- annot$dgelist
# # dgelist_col <- annot$dgelist
# # individual_list <- annot$Individual
```


```{r H3K27acSeq_FeatureCounts_RMG0_No4_RUV_StartingPCA}
# 
# #now plot my PCA for filtered counts
# ####PC1/PC2####
# individual_list <- H3K27ac_Metadata_No4_RUV$Individual
# 
# suppressWarnings(
#   ggplot2::autoplot(prcomp_res_log2,
#                     data = annot,
#                     colour = "Timepoint",
#                     shape = "Species",
#                     size = 4,
#                     x = 1,
#                     y = 2) +
#     scale_color_manual(values = ann_colors_No4$timepoint_cor) +
#     ggrepel::geom_text_repel(
#       label = individual_list,
#       vjust = -0.5,
#       max.overlaps = 50
#     ) +
#     ggtitle("H3K27ac log2cpm RMG0")
# )

```





```{r H3K27acSeq_FeatureCounts_RMG0_No4_RUV_RM1_PCA}
# set1 <- RUVSeq::RUVs(x = counts, k =1, scIdx = scIdx, isLog = FALSE)
# 
# # Get the RUV factors (weights) for modeling
# RUV_df1 <- set1$W %>% as.data.frame()
# RUV_df1$Condition <- rownames(RUV_df1)
# 
# RUV_df_rm1 <- RUV_df1[RUV_df1$Condition %in% annot$Condition, ]
# View(RUV_df_rm1)
# RUV_1 <- RUV_df_rm1$W_1
# 
# saveRDS(RUV_df_rm1, "data/QC/RUV_df_rm1.RDS")
# saveRDS(RUV_1, "data/QC/RUV_1.RDS")
# 
# 
# log2cpm_k1 <- cpm(set1$normalizedCounts, log = TRUE)
# 
# prcomp_res_log2_k1 <- prcomp(t(log2cpm_k1), scale=FALSE, center = TRUE)
# annot_prcomp_res_k1 <- prcomp_res_log2_k1$x %>% cbind(., H3K27ac_Metadata_No4)
# #PCA checks
# #k=1
# 
# ggplot2::autoplot(prcomp_res_log2_k1,
#                   data = annot_prcomp_res_k1,
#                   colour = "Timepoint",
#                   shape = "Species",
#                   size = 4,
#                   x=1,
#                   y=2) +
#   scale_color_manual(values=ann_colors_No4$timepoint_cor)+
#   ggrepel::geom_text_repel(label = individual_list,
#                             vjust = -0.5,
#                             max.overlaps = 50)+
#   ggtitle("RUV Correction k=1 log2cpm")

```



```{r Updating Website, eval = FALSE}

# git -> commit all changes
# git -> push
# wflow_publish("analysis/H3K27ac_CorrelationHeatMap_Ensemble.Rmd")

```


